on:
  push:

jobs:
  make_store:
    strategy:
      matrix:
        conf:
          - arch: aarch64
            machine: raspberrypi4-64
          - arch: aarch64
            machine: qemuarm-64
          - arch: amd64
            machine: generic-x86-64
    env:
      MACHINE: "${{ matrix.conf.machine }}"
      ARCH: "${{ matrix.conf.arch }}"
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-backports
      options: --privileged
      volumes:
        - /__w 
    steps:
      - name: Install dependencies
        run: |-
          apt -qqy update && \
            apt -qqy --no-install-recommends install ca-certificates make golang-1.22 git jq xz-utils libguestfs-tools linux-image-amd64 && \
            ln -s /usr/lib/go-1.22/bin/go /usr/bin/go

      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make
        env:
          DISG_NO_UNSHARE: y
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.conf.arch }}-${{ matrix.conf.machine }}--hassio-store"
          path: out/*.img.xz
          retention-days: 1

  upload_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: make_store
    container: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          set -x
          apt -qqy update && \
          apt -qqy --no-install-recommends install ca-certificates npm git tree && \
          npm install --global conventional-changelog-conventionalcommits@6 @semantic-release/git semantic-release@22
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*--hassio-store"
          merge-multiple: true
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
